# Generated by Django 4.2.7 on 2023-12-21 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("name", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.DeleteModel(name="Country",),
        migrations.DeleteModel(name="Email",),
    ]
