# Generated by Django 4.2.7 on 2024-01-03 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile", old_name="admin", new_name="is_staff",
        ),
        migrations.RenameField(
            model_name="userprofile", old_name="staff", new_name="is_superuser",
        ),
    ]
