# Generated by Django 4.2.7 on 2024-01-12 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0002_userprofile_groups_userprofile_user_permissions"),
    ]

    operations = [
        migrations.RemoveField(model_name="georgia_customer", name="id",),
        migrations.RemoveField(model_name="georgia_customer", name="user_profile",),
        migrations.AddField(
            model_name="georgia_customer",
            name="customer_ptr",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="registration.customer",
            ),
        ),
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(
                choices=[
                    ("N/A", "Not Applicable"),
                    ("USA", "United States"),
                    ("GE", "Georgia"),
                ],
                max_length=250,
                unique=True,
            ),
        ),
        migrations.DeleteModel(name="US_Customer",),
    ]
