# Generated by Django 4.2.7 on 2024-01-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0003_remove_georgia_customer_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(
                choices=[
                    ("Not Applicable", "Not Applicable"),
                    ("United States", "United States"),
                    ("Georgia", "Georgia"),
                ],
                max_length=250,
                unique=True,
            ),
        ),
    ]
