# Generated by Django 4.2.7 on 2024-01-23 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0004_alter_country_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
