# Generated by Django 4.2.7 on 2024-02-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0005_alter_country_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="phonenumber",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
