# Generated by Django 4.2.7 on 2024-02-01 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0006_customer_phonenumber"),
    ]

    operations = [
        migrations.RemoveField(model_name="georgia_customer", name="customer_ptr",),
        migrations.AddField(
            model_name="georgia_customer",
            name="customer",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="registration.customer",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="georgia_customer",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="georgia_customer",
            name="user_profile",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
